<?php

namespace Database\Seeders;

use App\Models\Events;
use Illuminate\Database\Seeder;

class EventsSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        Events::insert([
            [
                'name' => 'Chapel Night',
                'content' => "## Tentang Event\n\n🌙 Nikmati malam penuh keajaiban di Chapel Night, acara yang menghadirkan musik akustik, seni cahaya, dan atmosfer yang menenangkan.\n\nBersantai di bawah bintang-bintang dengan alunan musik yang menghanyutkan, ditemani dengan berbagai pilihan kuliner khas malam hari. 🎶✨\n\n🗓️ 20 Juni 2022\n📍 Lokasi: Chapel Garden, Yogyakarta\n\nRasakan pengalaman malam yang magis hanya di Chapel Night!",
                'categories' => json_encode(['Festival', 'Fair', 'Bazaar']),
                'themes' => json_encode(['Kuliner', 'Fashion', 'Kecantikan & Perawatan Diri']),
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1100,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area food court City Mall',
                'company_profile_id' => 1,
                'url' => '/events/chapel-night.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Big Festival',
                'content' => "## Tentang Event\n\n🎉 Sambut The Big Festival, ajang spektakuler yang akan membawa pengalaman tak terlupakan!\n\nDari konser musik, kompetisi seni, hingga bazar makanan eksklusif, semua ada di sini. Ajak teman dan keluarga untuk bergabung dalam perayaan terbesar tahun ini! 🎤🎭🎡\n\n🗓️ 5 - 7 Mei 2023\n📍 Lokasi: Central Park, Bandung\n\nSiapkan dirimu untuk merasakan festival dengan energi luar biasa!",
                'categories' => json_encode(['Festival', 'Fair', 'Bazaar']),
                'themes' => json_encode(['Kuliner', 'Fashion', 'Kecantikan & Perawatan Diri']),
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1000,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area utama City Mall',
                'company_profile_id' => 1,
                'url' => '/events/big-festival.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FIP FEST 2021',
                'content' =>  "## Tentang Event\n\n✨ Selamat datang di FIP FEST 2021, festival tahunan yang menghadirkan berbagai kegiatan seru!\n\nNikmati berbagai pertunjukan seni, pameran inovasi, serta bazar makanan dan fashion yang sayang untuk dilewatkan. 🎶🎨🍽️\n\n🗓️ 12 - 14 Agustus 2021\n📍 Lokasi: Kampus FIP, Jakarta\n\nJangan lewatkan keseruannya dan jadilah bagian dari momen istimewa ini!",
                'categories' => json_encode(['Festival', 'Fair', 'Bazaar']),
                'themes' => json_encode(['Kuliner', 'Fashion', 'Kecantikan & Perawatan Diri']),
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1600,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Lantai 2 City Mall',
                'company_profile_id' => 1,
                'url' => '/events/FIP-fest.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bazar Dialog',
                'content' => "## Tentang Event\n\n🛍️ Selamat datang di Bazar Dialog, tempat bertemunya kreativitas, bisnis lokal, dan komunitas yang dinamis!\n\nDapatkan berbagai produk unik dari pengrajin lokal, cicipi aneka kuliner khas, serta nikmati diskusi dan talkshow inspiratif bersama para ahli di bidangnya. 🛒🎙️\n\n🗓️ 10 - 12 September 2024\n📍 Lokasi: Plaza Senayan, Jakarta\n\nJangan lewatkan kesempatan untuk mengeksplorasi dan mendukung produk lokal terbaik!",
                'categories' => json_encode(['Festival', 'Fair', 'Bazaar']),
                'themes' => json_encode(['Kuliner', 'Fashion', 'Kecantikan & Perawatan Diri']),
                'registration_start' => '2025-02-21',
                'registration_end' => '2025-03-05',
                'event_start' => '2025-03-25',
                'event_end' => '2025-03-30',
                'time' => '10:00 - 21:00',
                'estimated_visitors' => 1000,
                'location' => 'City Mall, Jakarta',
                'city' => 'Jakarta',
                'detailed_location' => 'Area pameran City Mall',
                'company_profile_id' => 1,
                'url' => '/events/bazar-dialog.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Street Fair",
                'content' => "## Tentang Event\n\n✨ Selamat datang di Street Fair 2008, tempat di mana kreativitas dan komunitas bertemu!\n\nBergabunglah dalam perayaan jalanan terbesar tahun ini, menghadirkan berbagai stand kuliner, fashion, seni, dan hiburan lokal yang tidak boleh Anda lewatkan! 🎭🎨\n\n🗓️ 24 November 2008\n📍 Lokasi: Jalan Raya Utama, Jakarta\n\nNikmati suasana yang meriah dan jadikan momen ini tak terlupakan!",
                'categories' => json_encode(['Festival', 'Fair', 'Bazaar']),
                'themes' => json_encode(['Kuliner', 'Seni', 'Hiburan']),
                'registration_start' => "2008-10-01",
                'registration_end' => "2008-11-15",
                'event_start' => "2008-11-24",
                'event_end' => "2008-11-24",
                'time' => "09:00 - 22:00",
                'estimated_visitors' => 5000,
                'location' => "Jalan Raya Utama, Jakarta",
                'city' => "Jakarta",
                'detailed_location' => "Area utama sepanjang jalan raya",
                'company_profile_id' => 1,
                'url' => "/events/street-fair-2008.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Festival Teater Ruang Publik",
                'content' => "## Tentang Event\n\n✨ Saksikan keajaiban seni peran di Festival Teater Ruang Publik 2024!\n\n🎭 Nikmati pertunjukan dari berbagai komunitas teater terbaik selama 7 hari penuh! Temukan cerita menarik, pertunjukan mendalam, dan pengalaman seni yang menginspirasi.\n\n🗓️ 3 - 10 Agustus 2024\n📍 Lokasi: Taman Budaya Jakarta\n\nJangan lewatkan kesempatan untuk menjadi bagian dari sejarah seni panggung!",
                'categories' => json_encode(['Seni & Budaya']),
                'themes' => json_encode(['Teater', 'Drama', 'Seni']),
                'registration_start' => "2024-06-01",
                'registration_end' => "2024-07-20",
                'event_start' => "2024-08-03",
                'event_end' => "2024-08-10",
                'time' => "14:00 - 22:00",
                'estimated_visitors' => 2000,
                'location' => "Taman Budaya Jakarta",
                'city' => "Jakarta",
                'detailed_location' => "Teater outdoor & indoor area",
                'company_profile_id' => 1,
                'url' => "/events/festival-teater-ruang-publik.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Meez Fest",
                'content' => "## Tentang Event\n\n🎉 Nikmati pengalaman festival terbaik di Meez Fest!\n\nAcara ini menghadirkan konser musik, bazar kuliner, dan berbagai hiburan lainnya untuk Anda!\n\n🗓️ 27 Agustus 2024\n📍 Lokasi: Tamarald Event Centre\n\nSiapkan diri Anda untuk pesta yang tak terlupakan!",
                'categories' => json_encode(['Festival', 'Musik', 'Hiburan']),
                'themes' => json_encode(['Musik', 'Kuliner', 'Seni']),
                'registration_start' => "2024-06-15",
                'registration_end' => "2024-08-10",
                'event_start' => "2024-08-27",
                'event_end' => "2024-08-27",
                'time' => "16:00 - 23:00",
                'estimated_visitors' => 4000,
                'location' => "Tamarald Event Centre",
                'city' => "Jakarta",
                'detailed_location' => "Hall utama",
                'company_profile_id' => 1,
                'url' => "/events/meez-fest.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Summer Fling 2024",
                'content' => "## Tentang Event\n\n☀️ Rasakan euforia musim panas di Summer Fling!\n\nFestival ini akan menghadirkan pertunjukan musik, aktivitas pantai, dan berbagai hiburan menyenangkan lainnya.\n\n🗓️ 23 Agustus 2024\n📍 Lokasi: Pantai Indah, Bali\n\nDatang dan rayakan musim panas dengan penuh kegembiraan!",
                'categories' => json_encode(['Festival', 'Musik', 'Outdoor']),
                'themes' => json_encode(['Musik', 'Alam', 'Hiburan']),
                'registration_start' => "2024-06-10",
                'registration_end' => "2024-08-15",
                'event_start' => "2024-08-23",
                'event_end' => "2024-08-23",
                'time' => "12:00 - 22:00",
                'estimated_visitors' => 5000,
                'location' => "Pantai Indah, Bali",
                'city' => "Bali",
                'detailed_location' => "Area pantai utama",
                'company_profile_id' => 1,
                'url' => "/events/summer-fling.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "World Music Day",
                'content' => "## Tentang Event\n\n🎶 Rayakan Hari Musik Dunia bersama para musisi berbakat dalam acara World Music Day The Fellowship!\n\n🎸 Berbagai genre musik akan menghiasi panggung dalam konser yang penuh warna dan semangat!\n\n🗓️ 24 Juni 2023\n📍 Lokasi: Central Park, Jakarta\n\nNikmati alunan musik dari berbagai belahan dunia dan bergabunglah dalam pesta musik yang luar biasa!",
                'categories' => json_encode(['Konser & Festival Musik']),
                'themes' => json_encode(['Musik', 'Hiburan']),
                'registration_start' => "2023-05-01",
                'registration_end' => "2023-06-20",
                'event_start' => "2023-06-24",
                'event_end' => "2023-06-24",
                'time' => "16:00 - 23:00",
                'estimated_visitors' => 3000,
                'location' => "Central Park, Jakarta",
                'city' => "Jakarta",
                'detailed_location' => "Panggung utama area outdoor",
                'company_profile_id' => 1,
                'url' => "/events/world-music-day.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Seminar Digital Marketing",
                'content' => "## Tentang Event\n\n📈 Tingkatkan wawasan digital Anda dengan menghadiri Seminar Digital Marketing 2022!\n\n🖥️ Para pakar industri akan berbagi wawasan mendalam tentang tren pemasaran digital terbaru dan strategi untuk meningkatkan engagement bisnis Anda!\n\n🗓️ 12 Januari 2022\n📍 Lokasi: Grand Convention Center, Jakarta\n\nJangan lewatkan kesempatan emas ini untuk membangun koneksi bisnis dan mengembangkan strategi pemasaran Anda!",
                'categories' => json_encode(['Seminar & Workshop']),
                'themes' => json_encode(['Digital Marketing', 'Bisnis', 'Teknologi']),
                'registration_start' => "2021-12-01",
                'registration_end' => "2022-01-10",
                'event_start' => "2022-01-12",
                'event_end' => "2022-01-12",
                'time' => "09:00 - 17:00",
                'estimated_visitors' => 800,
                'location' => "Grand Convention Center, Jakarta",
                'city' => "Jakarta",
                'detailed_location' => "Hall utama, lantai 2",
                'company_profile_id' => 1,
                'url' => "/events/seminar-digital-marketing.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "2019 Career & Internship Fair",
                'content' => "## Tentang Event\n\n🚀 **Kickstart your career at the 2019 Career & Internship Fair!**\n\nLooking for the perfect job or internship opportunity? This is the place to be! Connect with top companies, expand your professional network, and explore exciting career paths in various industries.\n\n🎯 Open for: \n- Fresh graduates & students\n- Professionals seeking new opportunities\n\n🗓 **January 3, 2019**\n📍 **National Weather Center**\n\nDon't miss out on this chance to meet recruiters, gain insights, and take the next step in your career journey!",
                'categories' => json_encode(['Career', 'Internship', 'Job Fair']),
                'themes' => json_encode(['Professional Networking', 'Career Development']),
                'registration_start' => "2018-12-01",
                'registration_end' => "2018-12-30",
                'event_start' => "2019-01-03",
                'event_end' => "2019-01-03",
                'time' => "09:00 - 17:00",
                'estimated_visitors' => 5000,
                'location' => "National Weather Center",
                'city' => "Washington, D.C.",
                'detailed_location' => "Main Hall, National Weather Center",
                'company_profile_id' => 1,
                'url' => "/events/career-internship-fair.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "School Holiday Fest",
                'content' => "## Tentang Event\n\n🎉 **Make your holidays unforgettable at the School Holiday Fest!**\n\nGet ready for a fun-filled celebration with exciting activities, games, and entertainment for all ages!\n\n🎡 Enjoy: \n- Interactive workshops\n- Live performances\n- Kids' adventure zones\n\n🗓 **December 7, 2023**\n📍 **Menara Great Eastern**\n\nJoin us for an amazing day of fun, laughter, and learning! Don't forget to bring your friends and family!",
                'categories' => json_encode(['Festival', 'Family', 'Holiday']),
                'themes' => json_encode(['Entertainment', 'Kids', 'Family Fun']),
                'registration_start' => "2023-11-01",
                'registration_end' => "2023-12-06",
                'event_start' => "2023-12-07",
                'event_end' => "2023-12-07",
                'time' => "10:00 - 18:00",
                'estimated_visitors' => 3000,
                'location' => "Menara Great Eastern",
                'city' => "Kuala Lumpur",
                'detailed_location' => "Grand Ballroom, Menara Great Eastern",
                'company_profile_id' => 1,
                'url' => "/events/school-holiday.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => "Afro Beat Events",
                'content' => "## Tentang Event\n\n🥁 **Experience the Rhythm of Africa at Afro Beat Events!**\n\nFeel the vibrant beats and dance to the soulful tunes of Afro music in this electrifying event!\n\n🎶 Featuring: \n- Live performances by top Afro artists\n- Dance workshops\n- Cultural exhibitions\n\n🗓 **January 27, 2024**\n📍 **To Be Announced**\n\nA night full of energy, culture, and unforgettable music! Don't miss the ultimate Afro music experience!",
                'categories' => json_encode(['Music', 'Dance', 'Culture']),
                'themes' => json_encode(['Afrobeat', 'Cultural Celebration', 'Live Music']),
                'registration_start' => "2023-12-01",
                'registration_end' => "2024-01-26",
                'event_start' => "2024-01-27",
                'event_end' => "2024-01-27",
                'time' => "18:00 - 23:00",
                'estimated_visitors' => 2000,
                'location' => "To Be Announced",
                'city' => "Lagos",
                'detailed_location' => "To Be Announced",
                'company_profile_id' => 1,
                'url' => "/events/afro-beat-events.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ]

        ]);
    }
}
